### ISSUE TITLE
Unable to add patients on the day they are born

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#4] opened 2022-04-16 08:30 UTC
I think its very common for hospitals to add patients on the day they are born. However, the program doesn't allow me to. Eg patient born on 15-4-2021 and registered 15-4-2021 which makes sense practically. 
![4de90efa5dbe0602e8f83fb91a7e6063.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/5e58b900-1f7d-4af0-a387-c0b0eb63c03a.png)

**Comment by nus-se-script** [comment] 2022-04-20 03:38
# Team's Response
You can add in patients that are a few minutes old as age 1. It does not make sense to have an age 0.
The reason you could not add the patient even after stating age as 1 was because of a bug related to the registration date issue #753.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># User is unable to input patients who have registered into the program on the same day
>
>The `add patient` command rejects the input if the date of registration provided is today. Although this is acknowledged by an error message to be intended behaviour, this does not seem to make much sense as the user cannot input patients who have just registered and must wait until the next day to do so.
>
>Steps to reproduce:
>1. Run the command `add patient /info s1122334c, charlie c, 22, M, 4 SMU Ave, 2000-01-01, <today's date>` where <today's date> is replaced with the actual date itself (e.g. 2022-04-16)
>
>Observed outcome: the input is rejected.
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S2/pe-interim#690] [original labels: severity.Medium type.FunctionalityBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>Yes this is a valid issue. Our implementation disregards today as an appropriate date of registration. Definitely something that we should fix!


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)



- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue type

Team chose [`type.FunctionalityBug`]
Originally [`type.FeatureFlaw`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------

**Closed as completed** 2023-12-09 09:11 UTC
Labels: severity.Medium, type.FeatureFlaw, status.Done
