### ISSUE TITLE
Parser class 

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#10] opened 2022-04-16 09:24 UTC
Incorrect return type in parser class: 'string (]' ?
![c9101ebee21a5c82ca4604103f8c7aa8.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/9cf7633d-ba2f-4004-9a22-db2a511e3552.png)

**Comment by nus-se-script** [comment] 2022-04-20 03:39
# Team's Response
No details provided by team.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Validator class diagram documentation errors
>
>**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
>Incorrect parameter types are shown/inconsistent and is confusing. Many different types of string(], string] string()] can be seen
>![956751bba2fce1df6daee0c0ab5806d7.png](https://raw.githubusercontent.com/nus-cs2113-AY2122S2/pe/master/files/8bb06010-3e33-447f-afa0-393fd664aecb.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2113-AY2122S2/pe-interim#476] [original labels: severity.Medium type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>No details provided by team.


# Items for the Tester to Verify
## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)



- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------
## :question: Issue severity

Team chose [`severity.VeryLow`]
Originally [`severity.Low`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

-------------------

**Closed as completed** 2023-12-09 09:11 UTC
Labels: severity.Low, type.DocumentationBug, status.Done
